### ISSUE TITLE
Colocar dataset no repositório

### ISSUE THREAD

**Issue by yurimalheiros** [aurenivia/ICDFPP#1]
O dataset está sendo baixado diretamente no notebook. Algum motivo para isso? O dataset é muito grande?

Se não houver nenhum obstáculo, seria melhor disponibilizar os arquivos do dataset no repositório.

**Comment by aurenivia** [comment]
O Dataset está sendo baixando diretamente do notebook, pois é um dataset que possui alguns dados sensíveis (nome das pessoas, etc)
os dados estão separados em vários datasets, que precisam ser mergidos antes de serem utilizados, e é necessária toda uma limpeza/preparação do dado antes dele poder ser utilizado efetivamente.

adicionarei um snapshot do dataset no momento atual dentro do repositório, com os dados sensíveis removidos.

**Comment by yurimalheiros** [comment]
> adicionarei um snapshot do dataset no momento atual dentro do repositório, com os dados sensíveis removidos.

Não precisa. Como os dados são sensíveis, acho sua decisão correta.

**Comment by aurenivia** [comment]
tá certo, professor. 
manterei a adição dos dados por meio do script.
